// Legal Metrology (Packaged Commodities) Rules, 2011 (as amended)
// Statutory declaration rules and validation specifications for packaged goods in India.

export const LEGAL_METROLOGY_RULES = [
  {
    id: 'commodityName',
    ruleNumber: 'Rule 6(1)(b)',
    title: 'Commodity Name',
    label: 'Generic / Common Name of Commodity',
    category: 'Identity',
    mandatory: true,
    description: 'The common or generic name of the commodity contained in the package must be clearly stated.',
    expectedFormat: 'Standard generic name (e.g., Whole Wheat Flour, Refined Sunflower Oil, Biscuit)',
    statutoryRef: 'Section 18, Legal Metrology Act, 2009 read with Rule 6(1)(b) of LM (PC) Rules, 2011',
  },
  {
    id: 'manufacturer',
    ruleNumber: 'Rule 6(1)(a)',
    title: 'Manufacturer / Packer / Importer Details',
    label: 'Name and Complete Address of Manufacturer / Packer / Importer',
    category: 'Identity',
    mandatory: true,
    description: 'Name and complete physical address of manufacturer, packer, or importer including premises, city, state, and pincode.',
    expectedFormat: 'Full company/packer name with complete physical address & valid PIN code',
    statutoryRef: 'Rule 6(1)(a) of Legal Metrology (Packaged Commodities) Rules, 2011',
  },
  {
    id: 'netQuantity',
    ruleNumber: 'Rule 6(1)(c) & Rule 12',
    title: 'Net Quantity',
    label: 'Net Quantity in Standard Units of Weight/Measure/Number',
    category: 'Quantity',
    mandatory: true,
    description: 'Net quantity must be declared in metric units (g, kg, ml, l, m, N, units) with proper numeral and symbol spacing.',
    expectedFormat: 'Standard metric notation (e.g., 500 g, 1 kg, 750 ml, 1 L, 10 N, 2 Units)',
    statutoryRef: 'Rule 6(1)(c) & Second Schedule of LM (PC) Rules, 2011',
  },
  {
    id: 'mrp',
    ruleNumber: 'Rule 6(1)(e)',
    title: 'Maximum Retail Price (MRP)',
    label: 'MRP (Inclusive of All Taxes)',
    category: 'Pricing',
    mandatory: true,
    description: 'Maximum Retail Price must include the mandatory clause "inclusive of all taxes" in Indian Currency (Rs. / ₹).',
    expectedFormat: 'Rs. XXX / ₹ XXX (incl. of all taxes) with optional Unit Sale Price (USP)',
    statutoryRef: 'Rule 6(1)(e) of Legal Metrology (Packaged Commodities) Rules, 2011',
  },
  {
    id: 'monthYear',
    ruleNumber: 'Rule 6(1)(d)',
    title: 'Date of Manufacture / Packing / Import',
    label: 'Month and Year of Manufacture / Packing / Import',
    category: 'Date',
    mandatory: true,
    description: 'Month and year in which the commodity is manufactured, pre-packed, or imported.',
    expectedFormat: 'MM/YYYY, Month YYYY, or MMM YYYY (e.g., 06/2026, June 2026, Aug-2026)',
    statutoryRef: 'Rule 6(1)(d) of Legal Metrology (Packaged Commodities) Rules, 2011',
  },
  {
    id: 'consumerCare',
    ruleNumber: 'Rule 6(1)(n)',
    title: 'Consumer Care / Redressal Details',
    label: 'Consumer Care Helpline, Email & Contact Address',
    category: 'Support',
    mandatory: true,
    description: 'Name, address, telephone number, and email ID of the person/office to contact in case of consumer complaint.',
    expectedFormat: 'Helpline No. / Phone, Email Address (e.g. care@domain.com), and Contact Office',
    statutoryRef: 'Rule 6(1)(n) of Legal Metrology (Packaged Commodities) Rules, 2011',
  },
  {
    id: 'countryOfOrigin',
    ruleNumber: 'Rule 6(10)',
    title: 'Country of Origin',
    label: 'Country of Origin (Mandatory for Imported / Recommended for Domestic)',
    category: 'Origin',
    mandatory: true,
    description: 'Country of origin or manufacture must be conspicuously declared on all pre-packaged commodities.',
    expectedFormat: 'Country name (e.g., Country of Origin: India / Made in India)',
    statutoryRef: 'Rule 6(10) of Legal Metrology (Packaged Commodities) Rules, 2011',
  },
  {
    id: 'expiryDate',
    ruleNumber: 'Rule 6(1)(h)',
    title: 'Best Before / Expiry Date',
    label: 'Best Before / Expiry / Use By Date (For Applicable Goods)',
    category: 'Date',
    mandatory: false,
    description: 'Best before or use by date for human consumption commodities, pharmaceuticals, cosmetics, or perishable goods.',
    expectedFormat: 'Best Before XX Months / Expiry: MM/YYYY / Use By DD/MM/YYYY',
    statutoryRef: 'Rule 6(1)(h) of LM (PC) Rules, 2011 & FSSAI Packaging Regulations',
  },
  {
    id: 'batchNumber',
    ruleNumber: 'Rule 6(1)(g)',
    title: 'Batch / Lot Number',
    label: 'Batch Number / Lot Identification',
    category: 'Traceability',
    mandatory: false,
    description: 'Batch number or lot number for quality tracking and regulatory traceability.',
    expectedFormat: 'Batch No. / Lot No. alphanumeric code (e.g., B.No. 26A-890)',
    statutoryRef: 'Rule 6(1)(g) of Legal Metrology (Packaged Commodities) Rules, 2011',
  },
]

export const COMMODITY_CATEGORIES = [
  'Packaged Food & Beverages',
  'Edible Oils & Fats',
  'Food Grains & Pulses',
  'Personal Care & Cosmetics',
  'Household & Cleaning',
  'Electronics & Hardware',
  'Textiles & Garments',
  'General Packaged Commodities',
]
